name: Deploy website
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest   
    steps:
    - uses: actions/checkout@v2
    - name: npm install & build react app
      run: |
        npm install
        npm run build
        echo "auroraeditor.com" > build/CNAME
        cp build/index.html build/404.html
        cp -r src/Assets build/Assets
      env:
        REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
        REACT_APP_GITHUB_TOKEN: ${{ secrets.REACT_APP_GITHUB_TOKEN }}
    - name: setup github env
      run: |
          git config --global user.name 'AuroraCompanyBot'
          git config --global user.email 'AuroraCompanyBot@users.noreply.github.com'
          git remote set-url --push origin https://AuroraCompanyBot:$BOT_TOKEN@github.com/AuroraEditor/auroraeditor.com
    - name: push to Github Pages
      run: |
        git --work-tree build add --all
        git commit -m "Automatic Deploy action"
        git push origin HEAD:gh-pages --force
